name: Test and Generate Coverage on Push

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies and Build Rollup
        run: npm i
#       - name: Run Tests
#         run: npm run test
      - name: Jest Code Coverage Badge
        uses: luk-schweizer/jest-code-coverage-badge-action@v1.0.1
        with:
          test-command: cross-env CI=1 react-scripts test --env=jsdom --coverage
