name: Test and Generate Coverage on Push

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm run test
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: . --all
