name: Test and Generate Coverage on Push

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node using nvm
        run: nvm use
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm run test
